baseURL: 'http://programmingaway.com/'
languageCode: 'en-us'
title: 'Programming Away'
theme: 'ananke'
resourceDir: '../resources'
publishDir: 'public'

DefaultContentLanguage: 'en'
SectionPagesMenu: 'main'
Paginate: 9
enableRobotsTXT: true

sitemap:
  changefreq: 'monthly'
  priority: 0.5
  filename: 'sitemap.xml'

params:
  author: 'Brian Ladner'
  favicon: '/images/Logo/favicon.ico'
  site_logo: '/images/Logo/logo.png'
  #description: 'My Programming Journey'
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: 'bg-black'
  cover_dimming_class: 'bg-black-20'
  featured_image: '/images/beach-top.jpg'
  recent_posts_number: 3
  commentoEnable: true
  disable_share: true
  ananke_socials:
    - name: 'github'
      url: 'https://github.com/ProgrammingAway'
    - name: 'linkedin'
      url: 'https://www.linkedin.com/in/brian-ladner-a8902bb/'
